/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as RivalsRouteImport } from './routes/rivals'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as MetricsRouteRouteImport } from './routes/metrics/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MetricsIndexRouteImport } from './routes/metrics/index'
import { Route as MetricsBallRouteImport } from './routes/metrics/ball'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const RivalsRoute = RivalsRouteImport.update({
  id: '/rivals',
  path: '/rivals',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRouteRoute = MetricsRouteRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsIndexRoute = MetricsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MetricsRouteRoute,
} as any)
const MetricsBallRoute = MetricsBallRouteImport.update({
  id: '/ball',
  path: '/ball',
  getParentRoute: () => MetricsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/metrics': typeof MetricsRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/compare': typeof CompareRoute
  '/rivals': typeof RivalsRoute
  '/team': typeof TeamRoute
  '/metrics/ball': typeof MetricsBallRoute
  '/metrics/': typeof MetricsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/compare': typeof CompareRoute
  '/rivals': typeof RivalsRoute
  '/team': typeof TeamRoute
  '/metrics/ball': typeof MetricsBallRoute
  '/metrics': typeof MetricsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/metrics': typeof MetricsRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/compare': typeof CompareRoute
  '/rivals': typeof RivalsRoute
  '/team': typeof TeamRoute
  '/metrics/ball': typeof MetricsBallRoute
  '/metrics/': typeof MetricsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/metrics'
    | '/admin'
    | '/compare'
    | '/rivals'
    | '/team'
    | '/metrics/ball'
    | '/metrics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/compare'
    | '/rivals'
    | '/team'
    | '/metrics/ball'
    | '/metrics'
  id:
    | '__root__'
    | '/'
    | '/metrics'
    | '/admin'
    | '/compare'
    | '/rivals'
    | '/team'
    | '/metrics/ball'
    | '/metrics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MetricsRouteRoute: typeof MetricsRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  CompareRoute: typeof CompareRoute
  RivalsRoute: typeof RivalsRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rivals': {
      id: '/rivals'
      path: '/rivals'
      fullPath: '/rivals'
      preLoaderRoute: typeof RivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics/': {
      id: '/metrics/'
      path: '/'
      fullPath: '/metrics/'
      preLoaderRoute: typeof MetricsIndexRouteImport
      parentRoute: typeof MetricsRouteRoute
    }
    '/metrics/ball': {
      id: '/metrics/ball'
      path: '/ball'
      fullPath: '/metrics/ball'
      preLoaderRoute: typeof MetricsBallRouteImport
      parentRoute: typeof MetricsRouteRoute
    }
  }
}

interface MetricsRouteRouteChildren {
  MetricsBallRoute: typeof MetricsBallRoute
  MetricsIndexRoute: typeof MetricsIndexRoute
}

const MetricsRouteRouteChildren: MetricsRouteRouteChildren = {
  MetricsBallRoute: MetricsBallRoute,
  MetricsIndexRoute: MetricsIndexRoute,
}

const MetricsRouteRouteWithChildren = MetricsRouteRoute._addFileChildren(
  MetricsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MetricsRouteRoute: MetricsRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  CompareRoute: CompareRoute,
  RivalsRoute: RivalsRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
